[profile.default]
src = "src"
out = "out"
libs = ["lib"]

rpc_endpoints = { eth = "https://eth-sepolia.g.alchemy.com/v2/geBzHW66UjTf1ptyFYpOR0EY1ZeMyQfU", arb = "https://arb-sepolia.g.alchemy.com/v2/geBzHW66UjTf1ptyFYpOR0EY1ZeMyQfU", zksync = "https://zksync-sepolia.g.alchemy.com/v2/geBzHW66UjTf1ptyFYpOR0EY1ZeMyQfU" }

remappings = [
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@chainlink/contracts-ccip/=lib/ccip/contracts/src/v0.8/ccip/',
    '@chainlink/local/=lib/chainlink-local/src/',
]
# '@openzeppelin-upgradeable=lib/openzeppelin-contracts-upgradeable',
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
